[package]
name = "fileorz"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "FileORZ Linux desktop binary (scaffold)"

[[bin]]
name = "fileorz"
path = "src/main.rs"

[dependencies]
fileorz-core = { path = "../fileorz-core" }
fileorz-i18n = { version = "0.1.0", path = "../fileorz-i18n" }
fileorz-linux = { path = "../fileorz-linux" }

[lints]
workspace = true
